version: "3.1"
services:
    python-ai-bot:
        build: 
          args:
            - PROJECT_NAME=${PROJECT_NAME} 
            - OPENAI_API_KEY=${OPENAI_API_KEY}
            - GraphQL_SITE=${GraphQL_SITE}
          dockerfile: Docker-Files/Dockerfile 
        working_dir: /var/www/html/${PROJECT_NAME}
        volumes:
            - "./Project:/var/www/html/${PROJECT_NAME}"
        ports: 
            - "7860:7860"
        env_file: 
            - .env

