version: "3.1"
services:
    python-ai-bot:
        build: 
          args:
            - PROJECT_NAME=${PROJECT_NAME} 
          dockerfile: Docker-Files/Dockerfile 
        working_dir: /var/www/html/${PROJECT_NAME}
        volumes:
            - "./Project:/var/www/html/${PROJECT_NAME}"
        env_file: 
            - .env

